pipeline {
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/iamusayev/jenkins-gradle.git"
            }
        }
        stage("Build") {
            steps {
                dir("jenkins-gradle") {
                    sh "gradle clean build"
                }
            }
        }
        stage("Test") {
            steps {
                dir("jenkins-gradle") {
                    sh "gradle test"
                }
            }
        }
        stage("Hey"){
            steps {
                echo "Hey"
            }
    }
}
}
