pipeline {
    agent any
    stages {
         stage("Clean Up"){
            steps {
                deleteDir()
            }
         }
         stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/iamusayev/jenkins-ci-with-gradle.git"
            }
         }
         stage("Build"){
            steps {
                dir("jenkins-ci-with-gradle") {
                    sh "mvn clean install"
                }
            }
         }
         stage("Test"){
            steps {
                dir("jenkins-ci-with-gradle") {
                    sh "mvn test"
                }
            }
         }
    }
}